mysite/cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r"^(?P<count>\d+)/(?P<goods_id>\d+)/add/$", views.add, name="add"),
    url(r"^list/$", views.list, name="list"),
    url(r"^(?P<goods_id>\d+)/delete/$", views.delete, name="delete"),
]

mysite/mysite/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
import xadmin
from xadmin.plugins import xversion
xadmin.autodiscover()
xversion.register_models()


urlpatterns = [
    # 用户模块
    url(r'^users/', include("users.urls", namespace="users")),
    # 店铺模块
    url(r'^store/', include('store.urls', namespace='store')),
    # 商品模块
    url(r'^goods/', include('goods.urls', namespace='goods')),
    # 购物车模块
    url(r'^cart/', include('cart.urls', namespace='cart')),
    # 订单模块
    url(r'^orders/', include('orders.urls', namespace='orders')),
    # 全文检索
    # url(r'^search/', include('haystack.urls')),
    # 后台管理系统
    # url(r'^admin/', admin.site.urls),
    url(r'^xadmin/', xadmin.site.urls)

]

mysite/orders/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r"^confirm/$", views.confirm, name='confirm'),
    url(r"^pay/$", views.pay, name='pay'),
    url(r"^done/$", views.done, name='done'),
    url(r"^list/$", views.list, name='list'),
    url(r"^(?P<o_id>\d+)/detail/$", views.detail, name='detail'),
    url(r"^delete/(?P<o_id>\d+)/$", views.delete, name="delete"),
]

mysite/users/urls.py
from django.conf.urls import url
from . import views

app_name = 'users'

urlpatterns = [
    # 用户登录
    url(r"^login/$", views.user_login, name="user_login"),
    # 主页
    url(r"^index/$", views.index, name="index"),
    # 用户注册
    url(r"^register/$", views.register, name="register"),
    # # 用户退出
    url(r"^logout/$", views.logout, name="logout"),
    # 产生验证码
    url(r"^createCode/$", views.createCode, name="createCode"),
    # 用户中心-信息页
    url(r'^user_center_info/$', views.user_center_info, name='user_center_info'),
    url(r'^user_alter_info/$', views.user_alter_info, name='user_alter_info'),
    url(r'^watch/$', views.watch, name='watch'),

    # 用户中心-密码修改页
    url(r'^set_password/$', views.set_password, name='set_password'),

    url(r'^add_address/$', views.add_address, name='add_address'),
    url(r'^address_list/$', views.address_list, name='address_list'),

]

mysite/goods/models.py
from django.db import models
import store


class GoodsType(models.Model):
    id = models.AutoField(primary_key=True, verbose_name='商品类型id')
    name = models.CharField(max_length=255,unique=True, verbose_name='商品类型名称')
    cover = models.ImageField(upload_to='static/images/goods', default='static/images/goods/14.jpg', verbose_name="商品图片")
    intro = models.TextField(verbose_name="商品类别描述")
    parent = models.ForeignKey('self', null=True, blank=True, verbose_name="父级类型", on_delete=models.CASCADE)


class Goods(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255,verbose_name="商品名称")
    # price = models.DecimalField()
    price = models.FloatField(verbose_name="商品单价")
    stock = models.IntegerField()
    count = models.IntegerField(default=0)
    createTime = models.DateTimeField(auto_now_add=True)
    intro = models.TextField()
    stores = models.ForeignKey(store.models.Store, on_delete=models.CASCADE, verbose_name="商品所属")
    goodsType = models.ForeignKey(GoodsType,on_delete=models.CASCADE, verbose_name="商品类型")


class GoodsImage(models.Model):
    id = models.AutoField(primary_key=True)
    path = models.ImageField(upload_to='static/images/goods', default='static/images/goods/14.jpg', verbose_name="商品图片")
    status = models.BooleanField(default=False,verbose_name="是否显示默认图片")
    intro = models.TextField(verbose_name="商品图片描述")
    goods = models.ForeignKey(Goods, on_delete=models.CASCADE, verbose_name="所属商品")

mysite/orders/models.py
from django.db import models
from django.contrib.auth.models import User


class Order(models.Model):
    id = models.AutoField(primary_key=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="订单所属用户")
    createTime = models.DateTimeField(auto_now_add=True)
    recv_name = models.CharField(max_length=100, verbose_name="收件人")
    recv_tel = models.CharField(max_length=50, verbose_name="收件人电话")
    recv_address = models.CharField(max_length=255, verbose_name="收件人复制")
    all_price = models.FloatField(verbose_name="订单总金额")
    remark = models.CharField(max_length=255, verbose_name="订单备注")


class OrderItem(models.Model):
    id = models.AutoField(primary_key=True)
    goods_img = models.CharField(max_length=255, verbose_name="商品图片")
    goods_name = models.CharField(max_length=100, verbose_name="商品名称")
    goods_price = models.FloatField(verbose_name="商品价格")
    goods_count = models.IntegerField(verbose_name="商品数量")
    goods_price_all = models.FloatField(verbose_name="商品总价")
    order = models.ForeignKey(Order, on_delete=models.CASCADE, verbose_name="订单")

mysite/orders/views.py
from django.shortcuts import render,redirect,reverse
from django.views.decorators.http import require_POST
from cart.models import Cart
from users.models import Address
from goods.models import Goods
from . import models


@require_POST
def confirm(request):
    g_ids = request.POST.getlist("g_id")
    myCart = Cart.objects.filter(pk__in=g_ids)
    addresses = Address.objects.filter(user=request.user)
    return render(request, "orders/confirm.html", {"myCart": myCart, "addresses": addresses})


def pay(request):
    pass


@require_POST
def done(request):
    c_ids = request.POST.getlist("c_id")
    print(c_ids)
    address_id = request.POST["address"]

    address = Address.objects.get(pk=address_id)
    carts = Cart.objects.filter(pk__in=c_ids)

    _address = address.province+"|"+address.city+"|"+ address.area +"|"+address.street+"|"+address.desc
    # 生成订单
    order = models.Order(recv_address=_address, user=request.user, recv_name=address.recv_name,recv_tel=address.recv_tel, all_price=0, remark='')
    order.save()
    allCount = 0
    for s in carts:
        g = s.goods
        orderItem = models.OrderItem(id=g.id, goods_img=g.goodsimage_set.all().first().path,\
                         goods_name=g.name, goods_price=g.price, goods_count=s.count,
                         goods_price_all=s.allTotal,order=order)
        orderItem.save()
        allCount += s.allTotal
    order.all_price = allCount

    order.save()
    return redirect(reverse("orders:list"))


def list(request):
    orders = models.Order.objects.filter(user=request.user)
    return render(request, "orders/list.html", {"orders": orders})


def detail(request, o_id):
    pass


def delete(request, o_id):

    try:
        od = models.Order.objects.filter(pk=o_id)
        od.delete()
        return render(request, "orders/delete.html", {})
    except Exception as e:
        print(e)

mysite/xadmin/views/delete.py
from django.core.exceptions import PermissionDenied
from django.db import transaction, router
from django.http import Http404, HttpResponseRedirect
from django.template.response import TemplateResponse
from django.utils import six
from django.utils.encoding import force_text
from django.utils.html import escape
from django.utils.translation import ugettext as _
from django.contrib.admin.utils import get_deleted_objects

from xadmin.util import unquote
from xadmin.views.edit import UpdateAdminView
from xadmin.views.detail import DetailAdminView
from xadmin.views.base import ModelAdminView, filter_hook, csrf_protect_m


class DeleteAdminView(ModelAdminView):
    delete_confirmation_template = None

    def init_request(self, object_id, *args, **kwargs):
        "The 'delete' admin view for this model."
        self.obj = self.get_object(unquote(object_id))

        if not self.has_delete_permission(self.obj):
            raise PermissionDenied

        if self.obj is None:
            raise Http404(_('%(name)s object with primary key %(key)r does not exist.') % {'name': force_text(self.opts.verbose_name), 'key': escape(object_id)})

        using = router.db_for_write(self.model)

        # Populate deleted_objects, a data structure of all related objects that
        # will also be deleted.
        (self.deleted_objects, model_count, self.perms_needed, self.protected) = get_deleted_objects(
            [self.obj], self.opts, self.request.user, self.admin_site, using)

    @csrf_protect_m
    @filter_hook
    def get(self, request, object_id):
        context = self.get_context()

        return TemplateResponse(request, self.delete_confirmation_template or
                                self.get_template_list("views/model_delete_confirm.html"), context)

    @csrf_protect_m
    @transaction.atomic
    @filter_hook
    def post(self, request, object_id):
        if self.perms_needed:
            raise PermissionDenied

        self.delete_model()

        response = self.post_response()
        cls_str = str if six.PY3 else basestring
        if isinstance(response, cls_str):
            response = HttpResponseRedirect(response)
        return response

    @filter_hook
    def delete_model(self):
        """
        Given a model instance delete it from the database.
        """
        self.log('delete', '', self.obj)
        self.obj.delete()

    @filter_hook
    def get_context(self):
        if self.perms_needed or self.protected:
            title = _("Cannot delete %(name)s") % {"name":
                                                   force_text(self.opts.verbose_name)}
        else:
            title = _("Are you sure?")

        new_context = {
            "title": title,
            "object": self.obj,
            "deleted_objects": self.deleted_objects,
            "perms_lacking": self.perms_needed,
            "protected": self.protected,
        }
        context = super(DeleteAdminView, self).get_context()
        context.update(new_context)
        return context

    @filter_hook
    def get_breadcrumb(self):
        bcs = super(DeleteAdminView, self).get_breadcrumb()
        bcs.append({
            'title': force_text(self.obj),
            'url': self.get_object_url(self.obj)
        })
        item = {'title': _('Delete')}
        if self.has_delete_permission():
            item['url'] = self.model_admin_url('delete', self.obj.pk)
        bcs.append(item)

        return bcs

    @filter_hook
    def post_response(self):

        self.message_user(_('The %(name)s "%(obj)s" was deleted successfully.') %
                          {'name': force_text(self.opts.verbose_name), 'obj': force_text(self.obj)}, 'success')

        if not self.has_view_permission():
            return self.get_admin_url('index')
        return self.model_admin_url('changelist')

mysite/orders/templates/orders/confirm.html
<!DOCTYPE html>
<html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>确认订单</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
	<link rel="stylesheet" href="/static/css/bootstrap.css">
	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript" src="/static/js/jquery-ui.min.js"></script>

    <script type="text/javascript" src="/static/js/slide.js"></script>

    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/bootstrap.js"></script>


</head>
<body style="background:#eee">
<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎{{ user.username }}来到拼多多!</div>
			<div class="fr">

				<div class="login_btn fl">
					<a href="{% url 'users:user_login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'users:register' %}">注册</a>
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'users:user_center_info' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'store:add' %}">用户开店</a>
					<span>|</span>
					<a href="{% url 'cart:list' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'orders:list' %}">我的订单</a>
					<span>|</span>
					<a href="{% url 'users:logout' %}">退出登录</a>
				</div>
			</div>
		</div>
	</div>
<a href="{% url 'users:index' %}"><img src="/static/images/logo.png" alt=""></a>

<div class="container">
    <h1 class="text-center">确认订单</h1>
    <form action="/orders/done/" method="post">
         {% csrf_token %}
        <table border="1" class="table text-center">

        {% for sc in myCart %}
            <input type="hidden" name="c_id" value="{{sc.id}}">
            <tr class="warning">
                <td style="vertical-align:middle;">商品名称：{{sc.goods.name}}</td>
                <td style="vertical-align:middle;"><img src="/{{sc.goods.goodsimage_set.all.first.path}}" alt=""></td>
                <td style="vertical-align:middle;">商品数量：{{sc.count}}</td>
                <td style="vertical-align:middle;">小计金额：¥ {{sc.allTotal}}</td>

                </tr>

        {% endfor %}


			{% for as in addresses %}
			<tr class="info">
			<td style="vertical-align:middle;" colspan="4">
            请选择收货地址

            收货人：{{as.recv_name}}-----
                收货电话号码： {{ as.recv_tel}}---
            地址：{{as.province }}
            {{as.city}}
            {{as.street}}
            {{as.desc}}
            {% if as.status  %}
            <input type="radio" name="address" checked value="{{as.id}}">
            {% else %}
            <input type="radio" name="address"  value="{{as.id}}">

            {% endif %}

        </td></tr>
			{% endfor %}

    </table>

        <input class="btn btn-warning btn-lg btn-block" type="submit" value="确认订单">

	</form>
</div>
<div class="footer">
		<div class="foot_link">
			<a href="#">关于我们</a>
			<span>|</span>
			<a href="#">联系我们</a>
			<span>|</span>
			<a href="#">招聘人才</a>
			<span>|</span>
			<a href="#">友情链接</a>
		</div>
		<p>CopyRight © 2019 北京拼多多信息技术有限公司 All Rights Reserved</p>
		<p>电话：010-51888    京ICP备 76327568号</p>
	</div>

</body>
</html>

mysite/orders/templates/orders/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<p>取消订单成功！！！!<br>点击 <a href="{% url 'orders:list' %}">立即返回 </a>  即可查看购物车商品</p>

</body>
</html>

mysite/orders/templates/orders/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

mysite/orders/templates/orders/list.html
<!doctype html>
<html lang="en">

<head>
<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
	<title>我的所有订单</title>
	<link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
	<link rel="stylesheet" href="/static/css/bootstrap.css">
	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript" src="/static/js/jquery-ui.min.js"></script>

    <script type="text/javascript" src="/static/js/slide.js"></script>

    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/bootstrap.js"></script>


</head>
<body style="background:#eee">
<div class="header_con">
		<div class="header">
			<div class="welcome fl">欢迎{{ user.username }}来到拼多多!</div>
			<div class="fr">

				<div class="login_btn fl">
					<a href="{% url 'users:user_login' %}">登录</a>
					<span>|</span>
					<a href="{% url 'users:register' %}">注册</a>
				</div>
				<div class="user_link fl">
					<span>|</span>
					<a href="{% url 'users:user_center_info' %}">用户中心</a>
					<span>|</span>
					<a href="{% url 'store:add' %}">用户开店</a>
					<span>|</span>
					<a href="{% url 'cart:list' %}">我的购物车</a>
					<span>|</span>
					<a href="{% url 'orders:list' %}">我的订单</a>
					<span>|</span>
					<a href="{% url 'users:logout' %}">退出登录</a>
				</div>
			</div>
		</div>
	</div>
<a href="{% url 'users:index' %}"><img src="/static/images/logo.png" alt=""></a>
<div class="container">
<table class="table table-hover text-center table-bordered">
    <h1 class="text-center">我的订单详情</h1><br>
{% for o in orders %}
    <tr class="info"><td>{{o.recv_name}}</td>
        <td>{{o.recv_tel}}</td>
    <td>{{o.address}}</td>

        <td>{{o.all_price}}</td>
        <td>{{o.remark}}</td>
		<td>
			<a class="btn btn-danger" href="{% url 'orders:delete' o.id %}">取消订单</a></td>
 </tr>


{% endfor %}
	<tr><td colspan="6">
		<button class="btn  btn-warning btn-block btn-lg">掏钱吧你</button>
	</td></tr>
</table>
    </div>




</body>
</html>

mysite/orders/templates/orders/pay.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>