mysite/cart/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r"^(?P<count>\d+)/(?P<goods_id>\d+)/add/$", views.add, name="add"),
    url(r"^list/$", views.list, name="list"),
    url(r"^(?P<goods_id>\d+)/delete/$", views.delete, name="delete"),
]

mysite/goods/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r"^add/$", views.add, name='add'),
    url(r"^(?P<g_id>\d+)/detail/$", views.detail, name='detail'),
    url(r"^findTypeByPId/$", views.findTypeByPId, name='findTypeByPId'),
]

mysite/mysite/urls.py
from django.conf.urls import url
from django.conf.urls import include
from django.contrib import admin
import xadmin
from xadmin.plugins import xversion
xadmin.autodiscover()
xversion.register_models()


urlpatterns = [
    # 用户模块
    url(r'^users/', include("users.urls", namespace="users")),
    # 店铺模块
    url(r'^store/', include('store.urls', namespace='store')),
    # 商品模块
    url(r'^goods/', include('goods.urls', namespace='goods')),
    # 购物车模块
    url(r'^cart/', include('cart.urls', namespace='cart')),
    # 订单模块
    url(r'^orders/', include('orders.urls', namespace='orders')),
    # 全文检索
    # url(r'^search/', include('haystack.urls')),
    # 后台管理系统
    # url(r'^admin/', admin.site.urls),
    url(r'^xadmin/', xadmin.site.urls)

]

mysite/users/urls.py
from django.conf.urls import url
from . import views

app_name = 'users'

urlpatterns = [
    # 用户登录
    url(r"^login/$", views.user_login, name="user_login"),
    # 主页
    url(r"^index/$", views.index, name="index"),
    # 用户注册
    url(r"^register/$", views.register, name="register"),
    # # 用户退出
    url(r"^logout/$", views.logout, name="logout"),
    # 产生验证码
    url(r"^createCode/$", views.createCode, name="createCode"),
    # 用户中心-信息页
    url(r'^user_center_info/$', views.user_center_info, name='user_center_info'),
    url(r'^user_alter_info/$', views.user_alter_info, name='user_alter_info'),
    url(r'^watch/$', views.watch, name='watch'),

    # 用户中心-密码修改页
    url(r'^set_password/$', views.set_password, name='set_password'),

    url(r'^add_address/$', views.add_address, name='add_address'),
    url(r'^address_list/$', views.address_list, name='address_list'),

]

mysite/goods/models.py
from django.db import models
import store


class GoodsType(models.Model):
    id = models.AutoField(primary_key=True, verbose_name='商品类型id')
    name = models.CharField(max_length=255,unique=True, verbose_name='商品类型名称')
    cover = models.ImageField(upload_to='static/images/goods', default='static/images/goods/14.jpg', verbose_name="商品图片")
    intro = models.TextField(verbose_name="商品类别描述")
    parent = models.ForeignKey('self', null=True, blank=True, verbose_name="父级类型", on_delete=models.CASCADE)


class Goods(models.Model):
    id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=255,verbose_name="商品名称")
    # price = models.DecimalField()
    price = models.FloatField(verbose_name="商品单价")
    stock = models.IntegerField()
    count = models.IntegerField(default=0)
    createTime = models.DateTimeField(auto_now_add=True)
    intro = models.TextField()
    stores = models.ForeignKey(store.models.Store, on_delete=models.CASCADE, verbose_name="商品所属")
    goodsType = models.ForeignKey(GoodsType,on_delete=models.CASCADE, verbose_name="商品类型")


class GoodsImage(models.Model):
    id = models.AutoField(primary_key=True)
    path = models.ImageField(upload_to='static/images/goods', default='static/images/goods/14.jpg', verbose_name="商品图片")
    status = models.BooleanField(default=False,verbose_name="是否显示默认图片")
    intro = models.TextField(verbose_name="商品图片描述")
    goods = models.ForeignKey(Goods, on_delete=models.CASCADE, verbose_name="所属商品")

mysite/users/models.py
from django.db import models
from django.contrib.auth.models import User


class UserInfo(models.Model):
    id = models.AutoField(primary_key=True)
    age = models.IntegerField(default=18, verbose_name='用户年龄')
    gender = models.CharField(max_length=10, default='男', verbose_name='用户性别')
    nickname = models.CharField(max_length=10, verbose_name='用户昵称')
    phone = models.CharField(max_length=50, default="123456", verbose_name='电话号码')
    headers = models.ImageField(upload_to='static/images/headers/', default='static/images/headers/default.jpg', verbose_name='用户头像', )
    # 一对一外键
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    class Meta:
        db_table = 'users_userinfo'
        verbose_name_plural = "用户"


class Address(models.Model):
    id = models.AutoField(primary_key=True)
    recv_name = models.CharField(max_length=100, verbose_name="收货人")
    recv_tel = models.CharField(max_length=20, verbose_name="收货电话")
    province = models.CharField(max_length=100, verbose_name="收货人省份")
    city = models.CharField(max_length=100, verbose_name="收货城市")
    area = models.CharField(max_length=255, verbose_name="收货人县区")
    street = models.CharField(max_length=255, verbose_name="收货人街道")
    status = models.BooleanField(default=False, verbose_name="是否是默认地址")
    desc = models.CharField(max_length=255, verbose_name="详细地址")
    user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="地址所属用户")

    class Meta:
        db_table = 'users_address'
        verbose_name_plural = "用户地址"

mysite/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.contrib import auth
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpResponse, JsonResponse
from django.views.decorators.http import require_GET,require_POST
from .models import UserInfo
from django.contrib.auth import hashers
# 分页
from django.core.paginator import Paginator
# 验证码
from . import models
from . import utils
from io import BytesIO
import re
from goods.models import GoodsType, Goods


# 验证码
def createCode(req):
    # 在内存中开辟空间用以生成临时的图片
    f = BytesIO()
    img, code = utils.create_code()
    req.session['code'] = code
    img.save(f, 'PNG')
    return HttpResponse(f.getvalue())


@login_required
def index(request):
    # 第一个一级类型数据
    good_type1 = GoodsType.objects.filter(pk=10001)
    good_type1_2 = GoodsType.objects.filter(parent=good_type1)
    goods1_list = Goods.objects.filter(goodsType__in=good_type1_2)


    # 第二个一级类型数据
    good_type2 = GoodsType.objects.filter(pk=10002)
    good_type2_2 = GoodsType.objects.filter(parent=good_type2)
    goods2_list = Goods.objects.filter(goodsType__in=good_type2_2)

    # 第三个一级类型数据
    good_type3 = GoodsType.objects.filter(pk=10003)
    good_type3_2 = GoodsType.objects.filter(parent=good_type3)
    goods3_list = Goods.objects.filter(goodsType__in=good_type3_2)

    # 第四个一级类型数据
    good_type4 = GoodsType.objects.filter(pk=10004)
    good_type4_2 = GoodsType.objects.filter(parent=good_type4)
    goods4_list = Goods.objects.filter(goodsType__in=good_type4_2)

    # 第五个一级类型数据
    good_type5 = GoodsType.objects.filter(pk=10005)
    good_type5_2 = GoodsType.objects.filter(parent=good_type5)
    goods5_list = Goods.objects.filter(goodsType__in=good_type5_2)

    # 第六个一级类型数据
    good_type6 = GoodsType.objects.filter(pk=10006)
    good_type6_2 = GoodsType.objects.filter(parent=good_type6)
    goods6_list = Goods.objects.filter(goodsType__in=good_type6_2)

    allGoodsType = GoodsType.objects.filter(parent__isnull=True)
    return render(request, "users/index.html", {"allGoodsType": allGoodsType,\
                                                "goods1_list": goods1_list,\
                                                "goods2_list": goods2_list,\
                                                "goods3_list": goods3_list,\
                                                "goods4_list": goods4_list,\
                                                "goods5_list": goods5_list,\
                                                "goods6_list": goods6_list})


# 用户注册
def register(request):
    if request.method == "GET":
        return render(request, 'users/register.html')
    elif request.method == "POST":
        username = request.POST['user_name'].strip()
        password = request.POST['pwd'].strip()
        confirm = request.POST['cpwd'].strip()
        email = request.POST.get("email")
        code = request.POST['code'].strip()
        if code != request.session['code']:
            return render(request, "users/register.html", {"error": "验证码错误，请重新输入"})
        if username == '':
            return render(request, 'users/register.html', {'error': '用户名不能为空！'})
        if len(password) < 6:
            return render(request, 'users/register.html', {'error': '密码小于6位'})
        if password != confirm:
            return render(request, 'users/register.html', {'error': '两次密码不一致！'})
        try:
            # 判断用户名是否已注册 get 查找到0或多条都会报错
            User.objects.get(username=username)
            return render(request, 'users/register.html', {'error': '用户名已存在'})
        except:
            try:
                user = User.objects.create_user(username=username, password=password, email=email)
                user.save()
                userinfo = models.UserInfo(user=user, )
                userinfo.save()
                # 跳转到登录页面
                # return redirect('user:user_login')
                return render(request, "users/login.html", {"error": "注册成功,请登录!"})
            except Exception as e:
                return render(request, "users/register.html", {"error": "注册失败!"})


# 用户登录
def user_login(request):
    if request.method == "GET":
        # 判断是否记住用户名
        if "username" in request.COOKIES:
            username = request.COOKIES.get("username")
            checked = "checked"
        else:
            username = ""
            checked = ""
        context = {
            "username": username,
            "checked": checked
        }
        return render(request, 'users/login.html', context)
    elif request.method == "POST":
        username = request.POST.get("username")
        # username = str(username).encode('utf-8')

        password = request.POST.get("pwd")
        if not all([username, password]):
            return render(request, "users/login.html", {"error": "数据不完整"})
        user = authenticate(username=username, password=password)

        if user is not None:

            login(request, user)
            request.session['loginUser'] = user

            # 登陆成功之后跳转到首页
            next_url = request.GET.get("next", reverse("users:index"))
            # 跳转到next_url
            response = redirect(next_url)
            # 判断是否记住用户名
            remember = request.POST.get("remember")
            if remember == "on":
                # 记住用户名
                response.set_cookie("username", username, max_age=7 * 24 * 3600)
            else:
                response.delete_cookie("username")
            return response
            # return render(request, "users/static_base.html", {})
        else:
            # 用户名或者密码错误
            return render(request, "users/login.html", {"error": "账户或密码有误"})


def user_alter_info(request):
    u_id = request.user.id
    user = models.UserInfo.objects.get(id=request.user.id)
    if request.method == "GET":

        return render(request, "users/user_alter_info.html", {})
    else:
        header = request.FILES.get("header")
        age = request.POST["age"]
        gender = request.POST["gender"]
        phone = request.POST["phone"].strip()
        nickname = request.POST["nickname"].strip()
        address = request.POST["address"].strip()
        # user = request.session["loginUser"]
        user.headers = header
        user.age = age
        user.gender = gender
        user.phone = phone
        user.nickname = nickname
        user.address = address
        if phone == '' or address == '':
            return render(request, "users/user_alter_info.html", {"msg":"电话或地址不能为空！"})
        else:
            user.save()
            request.session["login_user"] = user
            print(user.headers)
            return render(request, "users/user_center_info.html", {})


# 用户中心-信息页
@login_required
def user_center_info(request):
    return render(request, "users/user_center_info.html", {})


@login_required
def logout(request):
    auth.logout(request)
    # 跳转首页
    return redirect(reverse("users:user_login"))


# 修改密码

@login_required
def set_password(request):
    user = request.user
    if request.method == 'GET':
        return render(request, "users/set_password.html", {})
    elif request.method == 'POST':
        old_password = request.POST.get("old_password")
        new_password = request.POST.get("new_password")
        repeat_password = request.POST.get("repeat_password")
        if user.check_password(old_password):  # 检查密码是否正确
            if not new_password:
                return render(request, 'users/set_password.html', {"msg": "新密码不能为空!"})

            elif new_password != repeat_password:
                return render(request, 'users/set_password.html', {"msg": "两次密码不一致!"})

            else:
                user.password = hashers.make_password(new_password)  # 正式修改密码，自动加密
                user.save()
                return redirect("users:index")
        else:
            return render(request, 'users/set_password.html', {"msg":"原密码输入错误"})


def watch(request):
    return render(request, "users/watch.html", {})


def add_address(request):
    if request.method == "GET":
        return render(request, "users/add_address.html", {})
    else:
        recv_name = request.POST["recv_name"]
        recv_tel = request.POST["recv_tel"]
        province = request.POST["province"]
        city = request.POST["city"]
        area = request.POST["area"]
        street = request.POST["street"]
        desc = request.POST["desc"]

        try:
            # 这个地址设为默认
            request.POST["status"]
            addresses = models.Address.objects.filter(user=request.user)

            for address in addresses:
                address.is_default = False
                address.save()
            address = models.Address(recv_name=recv_name, recv_tel=recv_tel,
                           province=province,
                           city=city,
                           area=area,
                           street=street,
                           desc=desc,
                           user=request.user,
                           status=True)
            address.save()
        except:
            address = models.Address(recv_name=recv_name, recv_tel=recv_tel,
                                     province=province,
                                     city=city,
                                     area=area,
                                     street=street,
                                     desc=desc,
                                     user=request.user,
                                     status=True)
            address.save()
        return redirect(reverse("users:address_list"))


def address_list(request):
    addresses = models.Address.objects.filter(user=request.user)
    return render(request, "users/address_list.html", {"addresses":addresses})

mysite/users/templates/users/add_address.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>添加地址</title>
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/main.css">
	<link rel="stylesheet" href="/static/css/bootstrap.css">
	<script type="text/javascript" src="/static/js/jquery-1.12.4.min.js"></script>
	<script type="text/javascript" src="/static/js/jquery-ui.min.js"></script>

    <script type="text/javascript" src="/static/js/slide.js"></script>

    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/bootstrap.js"></script>
    <style>
    #basic-table td{  text-align: center;vertical-align:middle;}
    </style>

</head>
<body style="background:#eee">
<div class="header_con">
    <div class="header">
        <div class="welcome fl">欢迎来到拼多多!</div>
        <div class="fr">
            <div class="login_info fl">
                欢迎您：<em>张迈</em>
            </div>
            <div class="login_btn fl">
                <a href="{% url 'users:user_login' %}">登录</a>
                <span>|</span>
                <a href="{% url 'users:register' %}">注册</a>
                <span>|</span>
                <a href="{% url 'users:set_password' %}">修改密码</a>

            </div>
            <div class="user_link fl">
                <span>|</span>
                <a href="{% url 'users:user_center_info' %}">用户中心</a>
                <span>|</span>
                <a href="{% url 'cart:list' %}">我的购物车</a>
                <span>|</span>
                <a href="{% url 'orders:list' %}">我的订单</a>
            </div>
        </div>
    </div>
</div>
<div class="container">
    <h1>添加您的收货地址</h1>

    <form action="{% url 'users:add_address' %}" method="post">
        {% csrf_token %}
        <table class="table table-hover table-condensed text-center" id="basic-table">
        <tr class="warning">
        <td><h4>收货人：</h4></td><td><input type="text" name="recv_name" class="form-control"></td></tr>
        <tr><td><h4>电话：</h4></td><td><input type="text" name="recv_tel" class="form-control"></td></tr>
            <tr class="warning"><td><h4>省份：</h4></td><td><input type="text" name="province" class="form-control"></td></tr>
        <tr><td><h4>城市：</h4></td><td><input type="text" name="city" class="form-control"></td></tr>
        <tr class="warning"><td><h4>区县：</h4></td><td><input type="text" name="area" class="form-control"></td></tr>
            <tr ><td><h4>街道：</h4></td><td><input type="text" name="street" class="form-control"></td></tr>
        <tr class="warning"><td><h4>详细地址：</h4></td><td><input type="text" name="desc" class="form-control"></td></tr>
        <tr><td><h4>是否为默认地址：</h4>
        </td><td><input type="checkbox" name="status" value="true" class="form-control"></td></tr>
        <tr class="warning" ><td colspan="2"><input type="submit" value="添加地址" class=" form-control btn btn-primary "></td></tr>
    </table>
    </form>
</div>

<div class="footer">
    <div class="foot_link">
        <a href="#">关于我们</a>
        <span>|</span>
        <a href="#">联系我们</a>
        <span>|</span>
        <a href="#">招聘人才</a>
        <span>|</span>
        <a href="#">友情链接</a>
    </div>
    <p>CopyRight © 2016 北京拼多多信息技术有限公司 All Rights Reserved</p>
    <p>电话：010-****888    京ICP备*******8号</p>
</div>
</body>
</html>

mysite/users/templates/users/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block title %}拼多多-登录{% endblock title %}
{% block header_con %}{% endblock header_con %}
{% block search_bar %}{% endblock search_bar %}
{% block body %}
	<div class="login_top clearfix">
		<a href="index.html" class="login_logo"><img src="{% static 'images/logo.png' %}"></a>
	</div>
	<div class="login_form_bg">
		<div class="login_form_wrap clearfix">
			<div class="login_banner fl"></div>
			<div class="slogan fl">13亿用户 · 劝君上当</div>
			<div class="login_form fr">
				<div class="login_title clearfix">
					<h1>用户登录</h1>
					<a href="{% url 'users:register' %}">立即注册</a>
				</div>
				<h5 style="text-align: center;">{{ error }}</h5><br>
				<div class="form_input">
                    {# 不设置表单action时，提交表单时，会向浏览器地址栏中的地址提交数据 #}
					<form method="post"  action="{% url 'users:user_login' %}">
                        {% csrf_token %}
						<input type="text" name="username" class="name_input" value="{{ username }}" placeholder="请输入用户名">
						<div class="user_error">输入错误</div>
						<input type="password" name="pwd" class="pass_input" placeholder="请输入密码">
						<div class="pwd_error">输入错误</div>
						<div class="more_input clearfix">
							<input type="checkbox" name="remember" {{ checked }}>
							<label>记住用户名</label>
							<a href="#">忘记密码</a>
						</div>
						<input type="submit" name="" value="登录" class="input_submit">
					</form>
				</div>
			</div>
		</div>
	</div>
{% endblock body %}

mysite/users/templates/users/user_center_info.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>拼多多·用户中心</title>
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">

    <link rel="stylesheet" type="text/css" href="/static/css/main.css">
    <script src="/static/js/jquery.min.js"></script>
    <script src="/static/js/bootstrap.js"></script>
    <link rel="stylesheet" href="/static/css/bootstrap.css">

</head>
<body>
<div class="header_con">
    <div class="header">
        <div class="welcome fl">欢迎来到拼多多!</div>
        <div class="fr">
            <div class="login_info fl">
                欢迎您：<em>张迈</em>
            </div>
            <div class="login_btn fl">
                <a href="{% url 'users:user_login' %}">登录</a>
                <span>|</span>
                <a href="{% url 'users:register' %}">注册</a>
                <span>|</span>
                <a href="{% url 'users:set_password' %}">修改密码</a>

            </div>
            <div class="user_link fl">
                <span>|</span>
                <a href="{% url 'users:user_center_info' %}">用户中心</a>
                <span>|</span>
                <a href="{% url 'cart:list' %}">我的购物车</a>
                <span>|</span>
                <a href="{% url 'orders:list' %}">我的订单</a>
            </div>
        </div>
    </div>
</div>

<div class="search_bar clearfix">
    <a href="{% url 'users:index' %}" class="logo fl"><img src="/static/images/logo.png"></a>
    <div class="search_con fr">
        <input type="text" class="input_text fl" name="" placeholder="搜索商品">
        <input type="button" class="input_btn fr" name="" value="搜索">
    </div>
</div>

<div class="main_con clearfix">
    <div class="left_menu_con clearfix">
        <h3>用户中心</h3>
        <ul>
            <li><a href="{% url 'users:user_center_info' %}" class="active">· 个人信息</a></li>
            <li><a href="{% url 'users:watch' %}">· 最近浏览</a></li>
            <li><a href="{% url 'users:user_alter_info' %}" >· 修改个人信息</a></li>
        </ul>
    </div>
    <div class="right_content clearfix">
        <div class="info_con clearfix">
            <h3 class="common_title2">基本信息</h3>
            <table border="1" cellspacing="0" cellpadding="0"  class="table table-hover table-bordered table-striped">
                <tr><td><span>用户名称：</span>{{ user.username }}</td></tr>
                <tr><td><span>用户头像：</span><img src="/static/images/headers/default.jpg" alt="" style="height: 80px;width: 80px;border-radius: 50%"></td></tr>
                <tr><td><span>用户性别：</span>{{ user.userinfo.gender }}</td></tr>
                <tr><td><span>用户年龄：</span>{{ user.userinfo.age }}</td></tr>
                <tr><td><span>联系方式：</span>{{ user.userinfo.phone }}</td></tr>
                <tr><td><a href="{% url 'users:add_address' %}">用户地址</a></td></tr>
            </table>
        </div>





<div class="footer">
    <div class="foot_link">
        <a href="#">关于我们</a>
        <span>|</span>
        <a href="#">联系我们</a>
        <span>|</span>
        <a href="#">招聘人才</a>
        <span>|</span>
        <a href="#">友情链接</a>
    </div>
    <p>CopyRight © 2016 北京拼多多信息技术有限公司 All Rights Reserved</p>
    <p>电话：010-****888    京ICP备*******8号</p>
</div>

</body>
</html>

mysite/users/templates/users/watch.html
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en">
<head>
    <meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
    <title>拼多多·用户中心</title>
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
    <link rel="stylesheet" type="text/css" href="/static/css/main.css">
</head>
<body>
<div class="header_con">
    <div class="header">
        <div class="welcome fl">欢迎来到拼多多!</div>
        <div class="fr">
            <div class="login_info fl">
                欢迎您：<em>张迈</em>
            </div>
            <div class="login_btn fl">
                <a href="{% url 'users:user_login' %}">登录</a>
                <span>|</span>
                <a href="{% url 'users:register' %}">注册</a>
                <span>|</span>
                <a href="{% url 'users:set_password' %}">修改密码</a>

            </div>
            <div class="user_link fl">
                <span>|</span>
                <a href="{% url 'users:user_center_info' %}">用户中心</a>
                <span>|</span>
                <a href="{% url 'cart:list' %}">我的购物车</a>
                <span>|</span>
                <a href="{% url 'orders:list' %}">我的订单</a>
            </div>
        </div>
    </div>
</div>

<div class="search_bar clearfix">
    <a href="{% url 'users:index' %}" class="logo fl"><img src="/static/images/logo.png"></a>

    <div class="search_con fr">
        <input type="text" class="input_text fl" name="" placeholder="搜索商品">
        <input type="button" class="input_btn fr" name="" value="搜索">
    </div>
</div>

<div class="main_con clearfix">
    <div class="left_menu_con clearfix">
        <h3>用户中心</h3>
        <ul>
            <li><a href="{% url 'users:user_center_info' %}" >· 个人信息</a></li>
            <li><a href="{% url 'users:watch' %}" class="active">· 最近浏览</a></li>
            <li><a href="{% url 'users:user_alter_info' %}" >· 修改个人信息</a></li>
        </ul>
    </div>


        <h2 class="common_title2">最近浏览</h2>
        <div class="has_view_list">
            <ul class="goods_type_list clearfix">
                <li>
                    <a href="detail.html"><img src="/static/images/goods_clothes.jpg"></a>
                    <h4><a href="detail.html">清新可爱的古风美女衣服</a></h4>
                    <div class="operate">
                        <span class="prize">¥ 138.00</span>
                        <span class="unit">100kg</span>
                        <a href="#" class="add_goods" title="加入购物车"></a>
                    </div>
                </li>

                <li>
                    <a href="#"><img src="/static/images/goods_clothes01.jpg"></a>
                    <h4><a href="#">萝莉lo娘衣服长裙</a></h4>
                    <div class="operate">
                        <span class="prize">¥ 238.00</span>
                        <span class="unit">买一送一</span>
                        <a href="#" class="add_goods" title="加入购物车"></a>
                    </div>
                </li>

                <li>
                    <a href="#"><img src="/static/images/goods_clothes03.jpg"></a>
                    <h4><a href="#">刘亦菲同款古风长裙</a></h4>
                    <div class="operate">
                        <span class="prize">￥10.00</span>
                        <span class="unit">10.00/500g</span>
                        <a href="#" class="add_goods" title="加入购物车"></a>
                    </div>
                </li>

                <li>
                    <a href="#"><img src="/static/images/goods_clothes02.jpg"></a>
                    <h4><a href="#">姐妹装闺蜜装古风</a></h4>
                    <div class="operate">
                        <span class="prize">¥ 568.00</span>
                        <span class="unit">净重200kg</span>
                        <a href="#" class="add_goods" title="加入购物车"></a>
                    </div>
                </li>

                <li>
                    <a href="#"><img src="/static/images/goods/goods021.jpg"></a>
                    <h4><a href="#">大嘴巴子</a></h4>
                    <div class="operate">
                        <span class="prize">¥ 25.00</span>
                        <span class="unit">6.45/500g</span>
                        <a href="#" class="add_goods" title="加入购物车"></a>
                    </div>
                </li>
            </ul>
        </div>
    </div>
</div>



<div class="footer">
    <div class="foot_link">
        <a href="#">关于我们</a>
        <span>|</span>
        <a href="#">联系我们</a>
        <span>|</span>
        <a href="#">招聘人才</a>
        <span>|</span>
        <a href="#">友情链接</a>
    </div>
    <p>CopyRight © 2016 北京拼多多信息技术有限公司 All Rights Reserved</p>
    <p>电话：010-****888    京ICP备*******8号</p>
</div>

</body>
</html>